name: Check File Encoding

on: [ push, pull_request ]

jobs:
  check-encoding:
    runs-on: ubuntu-latest

    steps:
      - name: "[Git] Checkout repository"
        uses: actions/checkout@v2

      - name: "[-] Check Encoding is UTF-8"
        run: echo '! find $GITHUB_WORKSPACE -type f -name "*.properties" -exec file --mime {} \; | grep -v "charset=utf-8$"' | bash
